apiVersion: v1
kind: Namespace
metadata:
  name: arca-agency-banking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arca-agency-banking-portal
  namespace: arca-agency-banking
spec:
  selector:
    matchLabels:
      app: agency-banking-portal
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: agency-banking-portal
    spec:
      containers:
      - name: arca-agency-banking-portal
        image: ${REPOSITORY_TAG}
        resources:
          requests:
             memory: 512Mi
             cpu: 0.5
#         env:
#         - name: SPRING_PROFILES_ACTIVE
#           value: production-microservice
        imagePullPolicy: Always
#         readinessProbe:
#           httpGet:
#             path: /healthz
#             port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: arca-agency-banking-portal-svc
  namespace: arca-agency-banking

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: agency-banking-portal

  ports:
    - name: http
      port: 4200
 

  type: LoadBalancer
